baseURL: "https://404gle.cn/"
defaultContentLanguage: zh
title: ĀKURAI's
paginate: 5
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-163991976-1

permalinks:
  posts: essay/:filename

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: ĀKURAI's
  description: "互联网是一座坟墓"
  author: Akuraito
  images: ["images/og.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: true
  hidemeta: false
  disableScrollToTop: true

  assets:
    favicon: "/images/favicon.svg"
    favicon16x16: "/images/favicon.svg"
    favicon32x32: "/images/favicon.svg"
    apple_touch_icon: "/images/favicon.svg"
    safari_pinned_tab: "/images/favicon.svg"

  label:
    text: "ĀKURAI's"

  profileMode:
    enabled: true
    title: "ĀKURAI&#39;s"
    subtitle: "互联网是一座坟墓"
    imageUrl: "/images/avatar.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar
    buttons:
      - name: 友人
        url: /friends/
      - name: 关于
        url: /about/

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 20
    - identifier: search
      name: 搜索
      url: https://www.google.com/search?q=site%3A404gle.cn
      weight: 30

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true

  youtube:
    privacyEnhanced: true