baseURL: "https://404gle.cn/"
defaultContentLanguage: zh
title: ĀKURAI's
paginate: 5
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-163991976-1

permalinks:
  posts: essay/:filename

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: ĀKURAI's
  description: "互联网是一座坟墓"
  keywords: [Blog, akura, akuraito]
  author: Akuraito
  # author: ["Me", "You"] # multiple authors
  images: ["images/og.webp"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon.svg"
    favicon16x16: "/images/favicon.svg"
    favicon32x32: "/images/favicon.svg"
    apple_touch_icon: "/images/favicon.svg"
    safari_pinned_tab: "/images/favicon.svg"

  label:
    text: "ĀKURAI's"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "ĀKURAI&#39;s"
    subtitle: "互联网是一座坟墓"
    imageUrl: "/images/avatar.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar
    buttons:
      - name: 友人
        url: /friends/
      - name: 关于
        url: /about/


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 20
    - identifier: search
      name: 搜索
      url: /search/
      weight: 30


privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true

  youtube:
    privacyEnhanced: true

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

#git add -A
#git commit -m "first commit"
#git push -u origin main