baseURL: "https://404gle.cn/"
theme: PaperMod
title: ĀKURAI's
paginate: 5

buildDrafts: false
buildExpired: false
buildFuture: false
enableEmoji: true
enableRobotsTXT: true

permalinks:
  posts: posts/:filename

minify:
  disableXML: true
  minifyOutput: true

params:
  author: Akuraito
  description: "互联网是一座坟墓"
  images: ["images/og.png"]
  title: ĀKURAI's
  comments: true
  disableScrollToTop: true
  hideFooter: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true

  assets:
    disableHLJS: true
    favicon: "/images/favicon.svg"
    apple_touch_icon: "/images/favicon.svg"
    safari_pinned_tab: "/images/favicon.svg"

  profileMode:
    enabled: true
    title: "ĀKURAI's"
    subtitle: "互联网是一座坟墓"
    imageUrl: "/images/avatar.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar

  socialIcons:
    - name: "discord"
      url: "https://discord.gg/jVGAXYem6P"
    - name: "telegram"
      url: "https://dzen.ru/akuraito"
    - name: "rss"
      url: "/index.xml"

menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: about
      name: 关于
      url: /about/
      weight: 20
    - identifier: friends
      name: 友人
      url: /friends/
      weight: 30

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true

  youtube:
    privacyEnhanced: true